
#Auto Repair Kits Configs
[general]
	#Example, at default setting of 100 ticks, (1 second is 20 ticks), the repair kits will automatically repair player's gear every 5 seconds
	#Range: 1 ~ 5000
	repair_interval = 100

